#!/bin/bash

# Quick Browser Refresh Guide
# Since HMR is disabled, you need to manually refresh

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔄 Frontend Changes Not Visible? Here's How to Fix It"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  NOTE: HMR (Hot Module Reload) is DISABLED in this project"
echo "   (See frontend/vite.config.js: hmr: false)"
echo ""
echo "This means changes won't appear automatically. You need to:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 1: HARD REFRESH (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open your browser to: http://localhost:5173/api-settings"
echo ""
echo "2. Press one of these key combinations:"
echo "   • Chrome/Edge (Windows/Linux): Ctrl + Shift + R"
echo "   • Chrome/Edge (Mac): Cmd + Shift + R"
echo "   • Firefox (Windows/Linux): Ctrl + F5"
echo "   • Firefox (Mac): Cmd + Shift + R"
echo "   • Safari (Mac): Cmd + Option + R"
echo ""
echo "3. Wait 2-3 seconds for page to fully reload"
echo ""
echo "4. Scroll to 'Transformation Mappings' section"
echo ""
echo "5. Click '+ Create New Mapping'"
echo ""
echo "6. You should now see:"
echo "   ✓ Template selector dropdown"
echo "   ✓ '📚 Choose from Template Library or Upload Custom:'"
echo "   ✓ Optgroups: 🚢 Logistics, 💼 ERP"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 2: CLEAR CACHE (If hard refresh doesn't work)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Chrome/Edge:"
echo "  1. Press F12 (open DevTools)"
echo "  2. Right-click the refresh button"
echo "  3. Select 'Empty Cache and Hard Reload'"
echo ""
echo "Firefox:"
echo "  1. Press Ctrl+Shift+Delete (Windows) or Cmd+Shift+Delete (Mac)"
echo "  2. Select 'Cached Web Content'"
echo "  3. Click 'Clear Now'"
echo "  4. Refresh page"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 3: RESTART FRONTEND (Nuclear option)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this command:"
echo "  pkill -9 -f vite && sleep 2 && bash start-frontend.sh"
echo ""
echo "Then hard refresh your browser (Ctrl+Shift+R)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Verify Changes Loaded:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open DevTools (F12)"
echo ""
echo "2. Go to Console tab"
echo ""
echo "3. Type: document.querySelector('[value=\"-- Custom Upload --\"]')"
echo ""
echo "4. Press Enter"
echo ""
echo "5. If you see: <option value=\"\">-- Custom Upload --</option>"
echo "   → ✅ Changes loaded successfully!"
echo ""
echo "6. If you see: null"
echo "   → ❌ Changes not loaded - try clearing cache"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "What You Should See After Refresh:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In the 'Create New Mapping' modal:"
echo ""
echo "  Destination Schema XML *"
echo "  "
echo "  📚 Choose from Template Library or Upload Custom:"
echo "  ┌─────────────────────────────────────────────┐"
echo "  │ ▼ -- Custom Upload --                       │"
echo "  │   ─────────────────────────────             │"
echo "  │   🚢 Logistics Systems                      │"
echo "  │      CargoWise Universal Shipment (2011.11) │"
echo "  │   💼 ERP Systems                            │"
echo "  │      SAP IDoc Invoice (R3)                  │"
echo "  │      Oracle Fusion AP Invoice (12.2)        │"
echo "  └─────────────────────────────────────────────┘"
echo ""
echo "  [📄 Upload Destination Schema]  ← Only visible when '-- Custom Upload --' selected"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test the Template Selector:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Select 'CargoWise Universal Shipment (2011.11)' from dropdown"
echo ""
echo "2. You should see:"
echo "   ┌──────────────────────────────────────────────┐"
echo "   │ ✅ Using template:                           │"
echo "   │    CargoWise Universal Shipment              │"
echo "   │                                               │"
echo "   │ CargoWise One • UNIVERSAL_SHIPMENT • v2011.11│"
echo "   │                                               │"
echo "   │ [Switch to custom upload]                    │"
echo "   └──────────────────────────────────────────────┘"
echo ""
echo "3. File upload button should be HIDDEN"
echo ""
echo "4. Success message should appear at top of page:"
echo "   '✓ Template loaded: CargoWise Universal Shipment'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Still Not Working?"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check browser console for errors:"
echo "  1. Press F12"
echo "  2. Go to Console tab"
echo "  3. Look for red error messages"
echo ""
echo "Common issues:"
echo "  • 'Failed to fetch /api/templates' → Backend not running"
echo "  • 'Unexpected token' → JavaScript syntax error"
echo "  • '404 Not Found' → File not bundled by Vite"
echo ""
echo "Verify code changes are in place:"
echo "  grep -n 'Choose from Template Library' frontend/src/pages/ApiSettingsPage.jsx"
echo ""
echo "  Expected output:"
echo "  1098:                                        📚 Choose from Template Library or Upload Custom:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The code changes ARE in your files ✓"
echo "The frontend IS running on port 5173 ✓"
echo ""
echo "You just need to:"
echo "  1. Hard refresh your browser (Ctrl+Shift+R)"
echo "  2. Navigate to API Settings → Transformation Mappings"
echo "  3. Click '+ Create New Mapping'"
echo "  4. See the template selector!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
