AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend for the XML Transformation App

Resources:
  TransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        TransformApi:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: ANY # Use ANY to ensure OPTIONS requests are passed through

Outputs:
  TransformApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://transformapi.example.com/prod/api/"