AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rossumxml

  Sample SAM Template for rossumxml

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  TransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Timeout: 30 # <-- ADD THIS LINE
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/"
  TransformFunction:
    Description: "Transform Function ARN"
    Value: !GetAtt TransformFunction.Arn
  TransformFunctionIamRole:
    Description: "Implicit IAM Role created for Transform function"
    Value: !GetAtt TransformFunctionRole.Arn